#' ---
#' title: ABCDCon control analysis plot PS correlations
#' author: Halle R. Dimsdale-Zucker
#' output:
#'  html_document:
#'    toc: true
#'    toc_depth: 4
#'    toc_float:
#'      collapsed: false
#'      smooth_scroll: false
#'    number_sections: true
#'    theme: spacelab
#' ---

#+ initialize, warning = FALSE, message = FALSE
devtools::load_all()

# add dplyr with library()
# NB: this is non-standard
# correct way would be to make this script into a function,
# store in the R/ directory,
# and use @importFrom dplyr "%>%",
# but this is incompatible with getting in-line results with code in knitr output
library(dplyr)

#' # Setup
#' ## Load config file
project_dir <- ("../")
config <- yaml::yaml.load_file(paste0(project_dir, "config.yml"))

#' ## Set paths as variables
analyzed_mri_dir <- paste0(project_dir,halle::ensure_trailing_slash(config$directories$analyzed_mri))
raw_behavioral_dir <- paste0(project_dir,halle::ensure_trailing_slash(config$directories$raw_behavioral))
analyzed_behavioral_dir <- paste0(project_dir,halle::ensure_trailing_slash(config$directories$analyzed_behavioral))
dropbox_dir <- halle::ensure_trailing_slash(config$directories$dropbox_abcdcon)
graph_fpath_out <- paste0(halle::ensure_trailing_slash(dropbox_dir),
                          halle::ensure_trailing_slash("writeups"),
                          halle::ensure_trailing_slash("figures"))

#' ## Setup other variables
#' ### Flags
SAVE_GRAPHS_FLAG <-1

#+ label="Load data"
#' ## Load in PS data
# here, we're using single trial data for each subject (`spatial_trials` and `temporal_trials`)
# these dataframes are generated by `pattern_similarity_no_outlier_trials_load_data_btwn_runs` with MIXED_MODELS_FLAG = 1
# this will take ~4 hours to generate with five rois of interest
load(paste0(analyzed_mri_dir, halle::ensure_trailing_slash("multivariate_sanityCheck"), 'group_spatial_trial_patterns.RData'))
load(paste0(analyzed_mri_dir, halle::ensure_trailing_slash("multivariate_sanityCheck"), 'group_temporal_trial_patterns.RData'))

spatial_trials %>%
  dplyr::filter(subj == "s001", roi == "CA1_body", hemi =="left") -> tmp
ggplot2::ggplot(reshape2::melt(tmp), ggplot2::aes(row_name, col_name, fill = value)) + ggplot2::geom_tile() + ggplot2::theme(axis.text.x = ggplot2::element_blank())

# try plotting using `ggcorr`
library("GGally")
# to test:
nba = read.csv("http://datasets.flowingdata.com/ppg2008.csv")
ggcorr(nba)
# on my data
# try feeding it an existing correlation matrix
ggcorr(data = NULL, cor_matrix = cor(tmp$r, use = "everything"))
# maybe try moving around so formatted as a matrix?
tmp %>%
  dplyr::select(col_name, row_name, r)


# try plotting using `superheat`
devtools::install_github("rlbarter/superheat")
library("superheat")
# to test
superheat::superheat(mtcars,
          # scale the matrix columns
          scale = TRUE)
