#' ---
#' title: ABCDCon Matched Trial Numbers Plot ChiSq Distrbution
#' author: Halle R. Dimsdale-Zucker
#' output:
#'  html_document:
#'    toc: true
#'    toc_depth: 4
#'    toc_float:
#'      collapsed: false
#'      smooth_scroll: false
#'    number_sections: true
#'    theme: spacelab
#' ---

#+ initialize, warning = FALSE, message = FALSE
devtools::load_all()

# add dplyr with library()
# NB: this is non-standard
# correct way would be to make this script into a function,
# store in the R/ directory,
# and use @importFrom dplyr "%>%",
# but this is incompatible with getting in-line results with code in knitr output
library(dplyr)

#' # Setup
#' ## Load config file
project_dir <- ("../")
config <- yaml::yaml.load_file(paste0(project_dir, "config.yml"))

#' ## Set paths as variables
analyzed_mri_dir <- paste0(project_dir,halle::ensure_trailing_slash(config$directories$analyzed_mri))
raw_behavioral_dir <- paste0(project_dir,halle::ensure_trailing_slash(config$directories$raw_behavioral))
analyzed_behavioral_dir <- paste0(project_dir,halle::ensure_trailing_slash(config$directories$analyzed_behavioral))
dropbox_dir <- halle::ensure_trailing_slash(config$directories$dropbox_abcdcon)
graph_fpath_out <- paste0(halle::ensure_trailing_slash(dropbox_dir),
                          halle::ensure_trailing_slash("writeups"),
                          halle::ensure_trailing_slash("figures"))

#' ## Setup other variables
#' ### Flags
SAVE_GRAPHS_FLAG <- 1
chisq_signif <- 5.991 # for Chisq df =2 (from https://www.medcalc.org/manual/chi-square-table.php)

#+ label="Load data"
#' # Load in data
# these dataframes are generated by `control_analysis_matched_trial_numbers.R`
num_reps <- 1000
load(paste0(analyzed_mri_dir, sprintf('match_trialnums_%dreps_chisqvals.RData', num_reps)))

#' ## Peek at the data
head(all_chisq)

#' # Count the number of times the chi-square value would not have been significant
all_chisq %>%
  dplyr::filter(chisq_value <= chisq_signif)

#' # Plot a distribution
all_chisq %>%
  ggplot2::ggplot(ggplot2::aes(chisq_value)) +
  ggplot2::geom_histogram(binwidth = 0.1) +
  # draw a line at p = 0.05 for Chisq df =2 (from https://www.medcalc.org/manual/chi-square-table.php)
  ggplot2::geom_vline(xintercept = chisq_signif, color = "red")

ggplot2::ggsave(file.path(graph_fpath_out, "matched-trial-nums", sprintf("control_analysis_trial_nums_chisq_dist_%s.pdf", num_reps)),
                width = 6, height = 4)
