#' ---
#' title: ABCDCon Mixed models with control ROIs
#' author: Halle R. Dimsdale-Zucker
#' output:
#'  html_document:
#'    toc: true
#'    toc_depth: 4
#'    toc_float:
#'      collapsed: false
#'      smooth_scroll: false
#'    number_sections: true
#'    theme: spacelab
#' ---

#+ initialize, warning = FALSE, message = FALSE
devtools::load_all()

# add dplyr with library()
# NB: this is non-standard
# correct way would be to make this script into a function,
# store in the R/ directory,
# and use @importFrom dplyr "%>%",
# but this is incompatible with getting in-line results with code in knitr output
library(dplyr)

#' # Setup
#' ## Load config file
project_dir <- ("../")
config <- yaml::yaml.load_file(paste0(project_dir, "config.yml"))

#' ## Set paths as variables
analyzed_mri_dir <- paste0(project_dir,halle::ensure_trailing_slash(config$directories$analyzed_mri))
raw_behavioral_dir <- paste0(project_dir,halle::ensure_trailing_slash(config$directories$raw_behavioral))
analyzed_behavioral_dir <- paste0(project_dir,halle::ensure_trailing_slash(config$directories$analyzed_behavioral))
dropbox_dir <- halle::ensure_trailing_slash(config$directories$dropbox_abcdcon)
graph_fpath_out <- paste0(halle::ensure_trailing_slash(dropbox_dir),
                          halle::ensure_trailing_slash("writeups"),
                          halle::ensure_trailing_slash("figures"))

#' ## Setup other variables
#' ### Flags
SAVE_GRAPHS_FLAG <-1

#+ label="Load data"
#' ## Load in PS data
# here, we're using single trial data for each subject (`spatial_trials` and `temporal_trials`)
# these dataframes are generated by `pattern_similarity_no_outlier_trials_load_data_btwn_runs` with MIXED_MODELS_FLAG = 1
# this will take ~4 hours to generate with five rois of interest
load(paste0(analyzed_mri_dir, halle::ensure_trailing_slash("multivariate_sanityCheck"), 'group_spatial_trial_patterns.RData'))
load(paste0(analyzed_mri_dir, halle::ensure_trailing_slash("multivariate_sanityCheck"), 'group_temporal_trial_patterns.RData'))

#' ## List included subjects
unique(spatial_trials$subj)
unique(temporal_trials$subj)

#' # Mixed models setup
#' ## Notes
# **is it legit to interpret models that don't converge?**
# this would suggest no b/c the parameters aren't jointly unidentifiable (altho they say may it's okay if only care about fixed effects): http://stackoverflow.com/questions/26465215/random-slope-for-time-in-subject-not-working-in-lme4
# Ben Bolker's advice would be to NOT include a random slopes term if the model can't fit it
# see: http://stackoverflow.com/questions/26465215/random-slope-for-time-in-subject-not-working-in-lme4
# simplification of random effects term based on https://hlplab.wordpress.com/2009/05/14/random-effect-structure/

# fixed effects: condition, roi, condition*roi
# random effects: subj
#' ## Z-score single trials
spatial_trials_z <-
  spatial_trials %>%
  as.data.frame() %>%
  dplyr::mutate(z_r = halle::fisher_r_to_z(r))

temporal_trials_z <-
  temporal_trials %>%
  as.data.frame() %>%
  dplyr::mutate(z_r = halle::fisher_r_to_z(r))

#' ## Setup dataframes for all trials, combined into a single dataframe
# This will enable us to run sameVideo/sameHouse vs. diffVideo/sameHouse vs. diffVideo/diffHouse
all_trials_z <- NULL
all_trials_z <- dplyr::full_join(spatial_trials_z, temporal_trials_z, by = intersect(names(spatial_trials_z), names(temporal_trials_z)))
head(all_trials_z)

# rename the trials so they're easier to follow
all_trials_z_better_names <- all_trials_z
all_trials_z_better_names$condition <- car::recode(all_trials_z_better_names$condition, "'differentVideo_sameHouse' = 'diffVideo_sameHouse'; 'differentHouse_eitherRoom' = 'diffVideo_diffHouse' ; 'sameHouse_eitherRoom' = 'anyVideo_sameHouse'; 'sameVideo' = 'sameVideo_sameHouse'")
unique(all_trials_z_better_names$condition)

# filter so just have control ROIs
all_trials_body <-
  all_trials_z_better_names %>%
  dplyr::filter(roi %in% c("ERC", "subiculum")) %>%
  droplevels(.)

head(all_trials_body)
unique(all_trials_body$roi)

#' ## Save out datframe so can be used in other analyses
save(all_trials_z_better_names,file=paste0(analyzed_mri_dir, 'group_z_renamed_spatial_temporal_PS_by_trial_control_ROIs.RData'))

#' # Spatial and temporal conditions: sameVideo/sameHouse, diffVideo/sameHouse, diffVideo/diffHouse
#' ## Model setup
# even though this information is listed earlier when the variable is created,
# it's nice to remind ourselves what the dataframe looks like
# before we start doing stats on it
# these models drop the `anyVideo/sameHouse` condition
# remember, the `anyVideo_sameHouse` condition considers both `sameVideo_sameHouse` trials AND `diffVideo_sameHouse` trials
# but we've decided to define space as `diffVideo/sameHouse` vs `diffVideo/diffHouse`

#' ## filter so just have conditions of interest
all_trials_body_SVSH_DVSH_DVDH <- NULL
all_trials_body_SVSH_DVSH_DVDH <-
  all_trials_body %>%
  dplyr::filter(condition %in% c("sameVideo_sameHouse", "diffVideo_sameHouse", "diffVideo_diffHouse"))
head(all_trials_body_SVSH_DVSH_DVDH)
unique(all_trials_body_SVSH_DVSH_DVDH$condition)
unique(all_trials_body_SVSH_DVSH_DVDH$hemi)
unique(all_trials_body_SVSH_DVSH_DVDH$roi)

#' ### main effects w/o random slopes
lmm.all_cond_roi_hemi.no_random_slopes <- lme4::lmer(z_r ~ condition*roi + condition*hemi + roi*hemi + (1|subj), data = all_trials_body_SVSH_DVSH_DVDH, REML = FALSE)
summary(lmm.all_cond_roi_hemi.no_random_slopes)

#' ### 3-way interaction w/o random slopes
lmm.all_condXroiXhemi.no_random_slopes <- lme4::lmer(z_r ~ condition*roi*hemi + (1|subj), data = all_trials_body_SVSH_DVSH_DVDH, REML = FALSE)
summary(lmm.all_condXroiXhemi.no_random_slopes)

#' #### Model comparisons (ROI x Context Similarity x Hemisphere)
anova(lmm.all_cond_roi_hemi.no_random_slopes, lmm.all_condXroiXhemi.no_random_slopes)

#' # Left hemi only
all_trials_body_SVSH_DVSH_DVDH_left <-
  all_trials_body_SVSH_DVSH_DVDH %>%
  dplyr::filter(hemi == "left")

lmm.all_cond_roi.left <- lme4::lmer(z_r ~ condition + roi + (1|subj), data = all_trials_body_SVSH_DVSH_DVDH_left, REML = FALSE)
summary(lmm.all_cond_roi.left)

lmm.all_condXroi.left <- lme4::lmer(z_r ~ condition*roi + (1|subj), data = all_trials_body_SVSH_DVSH_DVDH_left, REML=FALSE)
summary(lmm.all_condXroi.left)

#' ## model comparisons (Left Hemi: ROI x Context Similarity)
anova(lmm.all_cond_roi.left, lmm.all_condXroi.left)


#' # Right hemi only
all_trials_body_SVSH_DVSH_DVDH_right <-
  all_trials_body_SVSH_DVSH_DVDH %>%
  dplyr::filter(hemi == "right")

lmm.all_cond_roi.right <- lme4::lmer(z_r ~ condition + roi + (1|subj), data = all_trials_body_SVSH_DVSH_DVDH_right, REML = FALSE)
summary(lmm.all_cond_roi.right)

lmm.all_condXroi.right <- lme4::lmer(z_r ~ condition*roi + (1|subj), data = all_trials_body_SVSH_DVSH_DVDH_right, REML=FALSE)
summary(lmm.all_condXroi.right)

#' ## model comparisons (Right Hemi: ROI x Context Similarity)
anova(lmm.all_cond_roi.right, lmm.all_condXroi.right)

#' # Test for interactions between conditions - Episodic Context Similarity
#' ## Print out what's in dataframe before start running stats
# yes, this is redundant with when the dataframe gets setup
# but better to be redundant and ensure you know what you're working with!
all_trials_body_temporal <- NULL
all_trials_body_temporal <-
  all_trials_body %>%
  dplyr::filter(condition %in% c("sameVideo_sameHouse", "diffVideo_sameHouse"))
head(all_trials_body_temporal)
unique(all_trials_body_temporal$condition)
unique(all_trials_body_temporal$hemi)
unique(all_trials_body_temporal$roi)

#' ## Model setup: Left
# Now, we need to follow up the significant 3-way interaction in left hemi
temporal_lmm_left <-
  all_trials_body_temporal %>%
  dplyr::filter(hemi == "left")

# print out what's in the dataframe so we're supersure before running stats
head(temporal_lmm_left)
unique(temporal_lmm_left$condition)
unique(temporal_lmm_left$roi)
unique(temporal_lmm_left$hemi)

# condition, roi
lmm.ss2 <- lme4::lmer(z_r ~ condition + roi + (1|subj), data = temporal_lmm_left, REML = FALSE)
summary(lmm.ss2)

# condition * roi
lmm.ss3 <- lme4::lmer(z_r ~ condition*roi + (1|subj), data = temporal_lmm_left, REML=FALSE)
summary(lmm.ss3)

#' ### Compare models (left: Episodic Context Similarity)
# roi and condition vs. roi*condition
# this is the most comparable analysis to the condition x roi x hemi interaction model we're trying to breakdown
anova(lmm.ss2, lmm.ss3)

#' ## Model setup: Right
temporal_lmm_right <-
  all_trials_body_temporal %>%
  dplyr::filter(hemi == "right")

# print out what's in the dataframe so we're supersure before running stats
head(temporal_lmm_right)
unique(temporal_lmm_right$condition)
unique(temporal_lmm_right$roi)
unique(temporal_lmm_right$hemi)

# condition, roi
lmm.ss2.right <- lme4::lmer(z_r ~ condition + roi + (1|subj), data = temporal_lmm_right, REML = FALSE)
summary(lmm.ss2.right)

# condition * roi
lmm.ss3.right <- lme4::lmer(z_r ~ condition*roi + (1|subj), data = temporal_lmm_right, REML=FALSE)
summary(lmm.ss3.right)

#' ### Compare models (right: Episodic Context Similarity)
# roi and condition vs. roi*condition
# this is the most comparable analysis to the condition x roi x hemi interaction model we're trying to breakdown
anova(lmm.ss2.right, lmm.ss3.right)

#' # Test for interactions between conditions - Spatial Context Similarity
#' ## Print out what's in dataframe before start running stats
# yes, this is redundant with when the dataframe gets setup
# but better to be redundant and ensure you know what you're working with!
all_trials_body_spatial <- NULL
all_trials_body_spatial <-
  all_trials_body %>%
  dplyr::filter(condition %in% c("diffVideo_sameHouse", "diffVideo_diffHouse"))
head(all_trials_body_spatial)
unique(all_trials_body_spatial$condition)
unique(all_trials_body_spatial$hemi)
unique(all_trials_body_spatial$roi)

#' ## Model setup: Left
spatial_lmm_left <-
  all_trials_body_spatial %>%
  dplyr::filter(hemi == "left")

# print out what's in the dataframe so we're supersure before running stats
head(spatial_lmm_left)
unique(spatial_lmm_left$condition)
unique(spatial_lmm_left$roi)
unique(spatial_lmm_left$hemi)

# condition, roi
lmm.ss2 <- lme4::lmer(z_r ~ condition + roi + (1|subj), data = spatial_lmm_left, REML = FALSE)
summary(lmm.ss2)

# condition * roi
lmm.ss3 <- lme4::lmer(z_r ~ condition*roi + (1|subj), data = spatial_lmm_left, REML=FALSE)
summary(lmm.ss3)

#' ### Compare models (left : Spatial Context Similarity)
# roi and condition vs. roi*condition
# this is the most comparable analysis to the condition x roi x hemi interaction model we're trying to breakdown
anova(lmm.ss2, lmm.ss3)

#' ## Model setup: Right
spatial_lmm_right <-
  all_trials_body_spatial %>%
  dplyr::filter(hemi == "right")

# print out what's in the dataframe so we're supersure before running stats
head(spatial_lmm_right)
unique(spatial_lmm_right$condition)
unique(spatial_lmm_right$roi)
unique(spatial_lmm_right$hemi)

# condition, roi
lmm.ss2.right <- lme4::lmer(z_r ~ condition + roi + (1|subj), data = spatial_lmm_right, REML = FALSE)
summary(lmm.ss2.right)

# condition * roi
lmm.ss3.right <- lme4::lmer(z_r ~ condition*roi + (1|subj), data = spatial_lmm_right, REML=FALSE)
summary(lmm.ss3.right)

#' ### Compare models (right: Spatial Context Similarity)
# roi and condition vs. roi*condition
# this is the most comparable analysis to the condition x roi x hemi interaction model we're trying to breakdown
anova(lmm.ss2.right, lmm.ss3.right)


#' # Plot
all_trials_body %>%
  dplyr::filter(condition != "anyVideo_sameHouse") %>%
  dplyr::filter(hemi == "left") %>%
  dplyr::mutate(roi_by_hemi = gsub("(.*?)_body", "left \\1", roi)) %>%
  dplyr::mutate(roi_trimmed = sub("_(3)_", "\\1", roi_by_hemi)) %>%
  dplyr::group_by(roi_trimmed, hemi, condition) %>%
  dplyr::summarise(mean = mean(r),
                   sd = sd(r),
                   n = length(r),
                   sem = sd(r)/sqrt(length(r))) %>%
  # re-order conditions
  dplyr::mutate(condition_ordered = factor(condition, levels = c("sameVideo_sameHouse", "diffVideo_sameHouse", "diffVideo_diffHouse"))) %>%
  # put one space between same/diff and video/house and TWO spaces between where we'll want a line break
  # this will help `gsub` only create 2 lines for each condition name rather than 4 lines
  dplyr::mutate(condition_renamed = car::recode(condition_ordered, "'diffVideo_sameHouse' = 'Different Video  Same House'; 'diffVideo_diffHouse' = 'Different Video  Different House' ; 'sameVideo_sameHouse' = 'Same Video  Same House'")) %>%
  dplyr::mutate(condition_renamed_ordered = factor(condition_renamed, levels = c("Same Video  Same House", "Different Video  Same House", "Different Video  Different House"))) %>%
  # based on https://www.r-bloggers.com/line-breaks-between-words-in-axis-labels-in-ggplot-in-r/
  dplyr::mutate(condition_breaks = gsub("  ", "\n", condition_renamed_ordered)) %>%
  ggplot2::ggplot(ggplot2::aes(x = condition_breaks, y = mean, fill = condition_breaks)) +
  ggplot2::geom_bar(stat = "identity") +
  ggplot2::facet_grid(. ~ roi_trimmed) +
  # to match colors from method figure:
  # "#CC6633" = orange (diff video, diff house)
  # "#CC6699" = fuscia (same video, same house)
  # "#66CC33" = green (different video, same house)
  ggplot2::scale_fill_manual(values = c("#CC6633", "#66CC33", "#CC6699")) +
  ggplot2::geom_errorbar(ggplot2::aes(ymax = mean + sem,
                                      ymin = mean - sem,
                                      width=0.10)) +
  ggplot2::ggtitle("Neural pattern similarity for spatial and episodic contexts") +
  ggplot2::ylab("Mean Pattern Similarity (r)") +
  ggplot2::theme(axis.text.x = ggplot2::element_text(size = 10, color = "black"), axis.title.x = ggplot2::element_blank(),
                 strip.text.x = ggplot2::element_text(size = 20),
                 axis.text.y = ggplot2::element_text(size = 10), axis.title.y = ggplot2::element_text(size = 20),
                 strip.text.y = ggplot2::element_text(size = 20),
                 legend.title = ggplot2::element_blank(), legend.text = ggplot2::element_blank(),
                 plot.title = ggplot2::element_blank(),
                 strip.background = ggplot2::element_blank()) +
  ggplot2::theme(legend.position = "none")

if(SAVE_GRAPHS_FLAG == 1){
  ggplot2::ggsave(file = paste0(dropbox_dir,
                                halle::ensure_trailing_slash("writeups"),
                                halle::ensure_trailing_slash("figures"),
                                "sameAll_sameSome_diffAll_left_control_ROIs.pdf"),
                  width=8, height=6)
}

#' # Plot right
all_trials_body %>%
  dplyr::filter(condition != "anyVideo_sameHouse") %>%
  dplyr::filter(hemi == "right") %>%
  dplyr::mutate(roi_by_hemi = gsub("(.*?)_body", "right \\1", roi)) %>%
  dplyr::mutate(roi_trimmed = sub("_(3)_", "\\1", roi_by_hemi)) %>%
  dplyr::group_by(roi_trimmed, hemi, condition) %>%
  dplyr::summarise(mean = mean(r),
                   sd = sd(r),
                   n = length(r),
                   sem = sd(r)/sqrt(length(r))) %>%
  # re-order conditions
  dplyr::mutate(condition_ordered = factor(condition, levels = c("sameVideo_sameHouse", "diffVideo_sameHouse", "diffVideo_diffHouse"))) %>%
  # put one space between same/diff and video/house and TWO spaces between where we'll want a line break
  # this will help `gsub` only create 2 lines for each condition name rather than 4 lines
  dplyr::mutate(condition_renamed = car::recode(condition_ordered, "'diffVideo_sameHouse' = 'Different Video  Same House'; 'diffVideo_diffHouse' = 'Different Video  Different House' ; 'sameVideo_sameHouse' = 'Same Video  Same House'")) %>%
  dplyr::mutate(condition_renamed_ordered = factor(condition_renamed, levels = c("Same Video  Same House", "Different Video  Same House", "Different Video  Different House"))) %>%
  # based on https://www.r-bloggers.com/line-breaks-between-words-in-axis-labels-in-ggplot-in-r/
  dplyr::mutate(condition_breaks = gsub("  ", "\n", condition_renamed_ordered)) %>%
  ggplot2::ggplot(ggplot2::aes(x = condition_breaks, y = mean, fill = condition_breaks)) +
  ggplot2::geom_bar(stat = "identity") +
  ggplot2::facet_grid(. ~ roi_trimmed) +
  # to match colors from method figure:
  # "#CC6633" = orange (diff video, diff house)
  # "#CC6699" = fuscia (same video, same house)
  # "#66CC33" = green (different video, same house)
  ggplot2::scale_fill_manual(values = c("#CC6633", "#66CC33", "#CC6699")) +
  ggplot2::geom_errorbar(ggplot2::aes(ymax = mean + sem,
                                      ymin = mean - sem,
                                      width=0.10)) +
  ggplot2::ggtitle("Neural pattern similarity for spatial and episodic contexts") +
  ggplot2::ylab("Mean Pattern Similarity (r)") +
  ggplot2::theme(axis.text.x = ggplot2::element_text(size = 10, color = "black"), axis.title.x = ggplot2::element_blank(),
                 strip.text.x = ggplot2::element_text(size = 20),
                 axis.text.y = ggplot2::element_text(size = 10), axis.title.y = ggplot2::element_text(size = 20),
                 strip.text.y = ggplot2::element_text(size = 20),
                 legend.title = ggplot2::element_blank(), legend.text = ggplot2::element_blank(),
                 plot.title = ggplot2::element_blank(),
                 strip.background = ggplot2::element_blank()) +
  ggplot2::theme(legend.position = "none")

if(SAVE_GRAPHS_FLAG == 1){
  ggplot2::ggsave(file = paste0(dropbox_dir,
                                halle::ensure_trailing_slash("writeups"),
                                halle::ensure_trailing_slash("figures"),
                                "sameAll_sameSome_diffAll_right_control_ROIs.pdf"),
                  width=8, height=6)
}

