#' ---
#' title: ABCDCon control analysis plot PS correlations
#' author: Halle R. Dimsdale-Zucker
#' output:
#'  html_document:
#'    toc: true
#'    toc_depth: 4
#'    toc_float:
#'      collapsed: false
#'      smooth_scroll: false
#'    number_sections: true
#'    theme: spacelab
#' ---

#+ initialize, warning = FALSE, message = FALSE
devtools::load_all()

# add dplyr with library()
# NB: this is non-standard
# correct way would be to make this script into a function,
# store in the R/ directory,
# and use @importFrom dplyr "%>%",
# but this is incompatible with getting in-line results with code in knitr output
library(dplyr)

#' # Setup
#' ## Load config file
project_dir <- ("../")
config <- yaml::yaml.load_file(paste0(project_dir, "config.yml"))

#' ## Set paths as variables
analyzed_mri_dir <- paste0(project_dir,halle::ensure_trailing_slash(config$directories$analyzed_mri))
raw_behavioral_dir <- paste0(project_dir,halle::ensure_trailing_slash(config$directories$raw_behavioral))
analyzed_behavioral_dir <- paste0(project_dir,halle::ensure_trailing_slash(config$directories$analyzed_behavioral))
dropbox_dir <- halle::ensure_trailing_slash(config$directories$dropbox_abcdcon)
dropbox_graph_fpath_out <- paste0(halle::ensure_trailing_slash(dropbox_dir),
                                  halle::ensure_trailing_slash("writeups"),
                                  halle::ensure_trailing_slash("figures"))
graph_fpath_out <- paste0(dropbox_graph_fpath_out, "plot-PS-matrices")
dir.create(graph_fpath_out) # will throw an error if this already exists

#' ## Setup other variables
#' ### Flags
SAVE_GRAPHS_FLAG <-1

#+ label="Load data"
#' ## Load in PS data
# here, we're using single trial data for each subject (`spatial_trials` and `temporal_trials`)
# these dataframes are generated by `pattern_similarity_no_outlier_trials_load_data_btwn_runs` with MIXED_MODELS_FLAG = 1
# this will take ~4 hours to generate with five rois of interest
load(paste0(analyzed_mri_dir, halle::ensure_trailing_slash("multivariate_sanityCheck"), 'group_spatial_trial_patterns.RData'))
load(paste0(analyzed_mri_dir, halle::ensure_trailing_slash("multivariate_sanityCheck"), 'group_temporal_trial_patterns.RData'))

tmp <- spatial_trials %>%
  dplyr::filter(subj == "s001", roi == "CA1_body", hemi =="left")

tmp_mtx <- tmp %>%
  tidyr::spread(col_name, r)
colnames(tmp_mtx) <- NULL # this is part of my hack to remove the labels

tmp_mtx_small <- tmp_mtx[178:183, 1:5]

# try using `ggcorr`
library("GGally")
GGally::ggcorr(data = tmp_mtx[,6:ncol(tmp_mtx)])
  # repeating blank based on:L https://stackoverflow.com/questions/28427572/manipulating-axis-titles-in-ggpairs-ggally
  # ggplot2::geom_text(label = rep('', ncol(tmp_mtx))) #this does not work

# try using `ggcorrplot`
# devtools::install_github("kassambara/ggcorrplot")
library("ggcorrplot")

ggcorrplot(tmp_mtx[,-1]) # do not plot labels column

# try using `ggplot::geom_tile`
# NEED TO FIGURE OUT HOW TO MAKE SPARSE MATRICES NOT LOOK SHITTY
spatial_trials %>%
  dplyr::filter(hemi == "left") %>%
  dplyr::filter(subj %in% c("s001", "s002", "s006", "s007", "s008")) %>%
  ggplot2::ggplot(ggplot2::aes(row_name, col_name, fill = r)) +
  ggplot2::geom_tile() +
  ggplot2::theme(axis.text.y = ggplot2::element_blank(), axis.title.y = ggplot2::element_blank(),
                 axis.text.x = ggplot2::element_blank(), axis.title.x = ggplot2::element_blank()) +
  ggplot2::facet_grid(subj ~ condition)
